# .github/workflows/scrape.yml

name: Scrape jobs

on:
  workflow_dispatch:

env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
  TITLE_FILTERS: "Product,Product Manager,Product Owner,Fraud,Payments"

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: node scripts/scrape.js
