name: Scrape Jobs
on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    # hard-code your actual filter keywords here instead of using a secret
    env:
      TITLE_FILTERS: "analyst"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Scrape jobs and insert into Supabase
        run: npm run scrape
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          # TITLE_FILTERS is inherited from the job-level env, so we remove the secret reference
